### ISSUE TITLE
scaler js 적용관련

### ISSUE THREAD

**Issue by yellowssun** [kw-kwix/pose-detector#1]
지금까지는 모델을 만들때만 스케일러를 사용하였는데 모델의 입력에 넣을때도 스케일러를 사용하게 코드를 수정했음.
실제로 실험해본 결과 인식률이 매우 좋아짐. 스케일러는 sklearn Normalizer를 사용했고, sklearn에도 js용 api가 있다는 것을 확인했음.
내 개인 repository에 수정한 코드를 올렸으니 참고해서 수정하면 될듯.

**Comment by yoonlight** [comment]
추가 완료
https://github.com/kw-kwix/pose-detector/commit/eb92b1066a09ebe9bcf40dcce1b67e6c243063a9?diff=split

그리고 앞으로 요청할 때 어디 부분 수정되었는지도 알려주세요.
https://github.com/kw-kwix/HAR_model
예를 들어 이 부분도 폴더 이름이 models 였는데 modeljs로 바꾸게 되면 이 코드에서도 수정이 필요합니다.

맨 위의 링크처럼 수정한 코드의 commit 부분을 올려 달라는 의미입니다.
